{% set name = "earthaccess" %}
{% set version = "0.13.0" %}
{% set sha256 = "40cf494b55afee953c50d41dfd232351b014112e382d2edd4f2583078a3f19d0" %}
{% set build_number = 0 %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/{{ name }}/earthaccess-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.25.0
  run:
    - python >={{ python_min }},<4.0
    - python-cmr >=0.10.0
    - pqdm >=0.1
    - requests >=2.26
    - s3fs >=2022.11
    - fsspec >=2022.11
    - tinynetrc >=1.3.1
    - multimethod >=1.8
    - python-dateutil >=2.8.2
    - importlib-resources >=6.3.2
    - typing_extensions >=4.10.0
    - numpy >=1.24.0 # TODO: since kerchunk is a transient dep we don't need to enforce 3.12 compatible version for numpy
    - kerchunk >=0.2.6
    - zarr >=2.12.0, <3.0.0a
    - virtualizarr >=1.2.0

test:
  imports:
    - earthaccess
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/earthaccess/
  summary: Client Library for NASA Earthdata APIs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mfisher87
    - jrbourbeau
    - jhkennedy
    - betolink
