{% set name = "earthaccess" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/{{ name }}/earthaccess-{{ version }}.tar.gz
  sha256: d62de1ea6ac78e299c645ac9884d2f15e31f7599d4db0eaebb4b900a0f9c8592

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - poetry >=0.12
  run:
    - python >=3.8,<4.0
    - python-cmr >=0.7
    - pqdm >=0.1
    - requests >=2.26
    - s3fs >=2021.11, <2024
    - fsspec >=2022.1
    - tinynetrc >=1.3.1
    - multimethod >=1.8

test:
  imports:
    - earthaccess
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/earthaccess/
  summary: Client Library for NASA Earthdata APIs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jhkennedy
    - betolink
