schema_version: 1

context:
  name: earthaccess
  version: "0.15.1"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/${{ name }}/earthaccess-${{ version }}.tar.gz
  sha256: 67ad29f7c8d54eb17ae92972e00d95f4bb2d78f6cadb770727384efc324f1fc5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - hatchling >=1.25.0
    - pip
    - python ${{ python_min }}.*
  run:
    - fsspec >=2022.11
    - importlib-resources >=6.3.2
    - kerchunk >=0.2.6
    - multimethod >=1.8
    - numpy >=1.24.0 # TODO: since kerchunk is a transient dep we don't need to enforce 3.12 compatible version for numpy
    - pqdm >=0.1
    - python >=${{ python_min }},<4.0
    - python-cmr >=0.10.0
    - python-dateutil >=2.8.2
    - requests >=2.26
    - s3fs >=2022.11
    - tinynetrc >=1.3.1
    - typing_extensions >=4.10.0
    - virtualizarr >=1.2.0
    - zarr >=2.12.0, <3.0.0a

tests:
  - python:
      imports:
        - earthaccess
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://earthaccess.readthedocs.io
  repository: https://github.com/nsidc/earthaccess
  summary: Client Library for NASA Earthdata APIs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - betolink
    - jhkennedy
    - jrbourbeau
    - mfisher87
    - weiji14
